"""initial config tables

Revision ID: 97ae2e41f01f
Revises: 
Create Date: 2026-07-09 15:57:03.521680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ae2e41f01f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_assumption_sets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.Enum('gifting', 'decor', name='brand'), nullable=True),
    sa.Column('filament_cost_per_kg', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('electricity_cost_per_unit', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('machine_hour_cost', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('finishing_labour', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('consumables', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('failure_pct', sa.Numeric(precision=5, scale=4, asdecimal=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machine_profiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('machine_hour_cost', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_profiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('material_type', sa.String(length=40), nullable=False),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('colour', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_profiles')
    op.drop_table('machine_profiles')
    op.drop_table('cost_assumption_sets')
    # ### end Alembic commands ###
