"""user invites

Admin-provisioned accounts. An admin names an email and a role; the invitee
follows a single-use link and sets their own password. No password is ever
generated for them or derived from their role.

`token_hash` stores only the SHA-256 of the token, never the token itself: an
invite grants a role, so a leaked table must not be a leaked account. There is
no index on token_hash because the unique constraint already provides one.

`accepted_user_id` holds a Better Auth user id and has no foreign key, for the
same reason as user_roles.user_id — that table belongs to Better Auth's CLI, not
Alembic.

Revision ID: a753367d3132
Revises: b1c4d7e93a02
Create Date: 2026-07-17 13:45:40.110024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a753367d3132'
down_revision: Union[str, Sequence[str], None] = 'b1c4d7e93a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invites',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_user_id', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_user_invites_email', 'user_invites', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_invites_email', table_name='user_invites')
    op.drop_table('user_invites')
    # ### end Alembic commands ###
