"""authz tables: roles, permissions, assignments

Hand-written rather than autogenerated, because `user_roles.user_id` points at
Better Auth's `user` table, which Alembic does not manage (see alembic/env.py's
include_object). Autogenerate cannot see that table and would produce a diff
that fights the frontend's migration.

There is deliberately no foreign key from user_roles.user_id to user.id: a
database constraint would couple this migration to Better Auth's CLI and force
a fixed apply order between two independent tools. An orphaned row is harmless
— no user means no token, which means no authorization.

Revision ID: b1c4d7e93a02
Revises: 97ae2e41f01f
Create Date: 2026-07-17

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1c4d7e93a02'
down_revision: Union[str, Sequence[str], None] = '97ae2e41f01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'roles',
        sa.Column('name', sa.String(length=40), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )

    op.create_table(
        'permissions',
        sa.Column('resource', sa.String(length=40), nullable=False),
        sa.Column('action', sa.String(length=40), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action'),
    )

    op.create_table(
        'role_permissions',
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.Column('permission_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    )

    op.create_table(
        'user_roles',
        # A Better Auth user id (cuid). Unconstrained on purpose - see docstring.
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('role_id', sa.Uuid(), nullable=False),
        sa.Column('assigned_by', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id'),
    )
    # Every token mint reads this by user_id, so it is the hot path.
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'])

    op.create_table(
        'user_authz_state',
        sa.Column('user_id', sa.String(length=64), nullable=False),
        sa.Column('permissions_version', sa.Integer(), server_default='1', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('user_authz_state')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    op.drop_table('roles')
